version: '3.8'
services:
  authority_controller:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
#    networks:
#      - election-network
#networks:
#  election-network:
#    external: true